# Generated by Django 2.2.4 on 2019-09-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apuntespy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='tag',
            new_name='tags',
        ),
    ]
