# Generated by Django 2.2.4 on 2019-09-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuntespy', '0002_auto_20190903_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='function_description',
            new_name='tip_descripcion',
        ),
        migrations.RenameField(
            model_name='tip',
            old_name='function_example',
            new_name='tip_ejemplo',
        ),
        migrations.RenameField(
            model_name='tip',
            old_name='function_name',
            new_name='tip_nombre',
        ),
        migrations.AlterField(
            model_name='tip',
            name='tags',
            field=models.ManyToManyField(related_name='tips', to='apuntespy.Tag'),
        ),
    ]
